apiVersion: apps/v1
kind: Deployment
metadata:
  name: pmml-deployment
  labels:
    app: pmml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pmml
  template:
    metadata:
      labels:
        app: pmml
    spec:
      containers:
      - name: pmml
        image: torarg/pmml:0.1.7
        volumeMounts:
        - mountPath: "/.pmmlrc"
          subPath: ".pmmlrc"
          name: "pmml-pmmlrc"
          readOnly: true
        - mountPath: "/.fetchmailrc"
          subPath: ".fetchmailrc"
          name: "pmml-fetchmailrc"
          readOnly: true
      volumes:
      - name: pmml-pmmlrc
        secret:
          secretName: pmml-pmmlrc
      - name: pmml-fetchmailrc
        secret:
          secretName: pmml-fetchmailrc
